### ISSUE TITLE
Indicate support for Quilt for beta.2

### ISSUE THREAD

**Issue by SoulxluoS** [opekope2/LiLaC#4]
![image](https://github.com/opekope2/LiLaC/assets/70120313/a2fbafd9-dd69-4cd9-8060-bbc7004a0f85)

**Comment by opekope2** [comment]
I haven't yet tested Quilt. Most likely works, but only an older version of QKL is available for older Quilt, which *might* be an issue. I plan to downgrade Kotlin dependency to definitely not crash. The "metadata changes" I mentioned in beta 1 covers this.

**Comment by opekope2** [comment]
Well bruh since I marked the first beta as Quilt-compatible, and it didn't crash after trying it, I marked it as compatible. Also added FAPI to Modrinth, because the CI isn't finished.
