### ISSUE TITLE
1.20.4 Support?

### ISSUE THREAD

**Issue by t0mtee** [opekope2/LiLaC#7]

**Comment by opekope2** [comment]
I only announced OptiGUI roadmap.
LiLaC is not a priority right now. I'll be back developing it (and OptiGUI 2.2.0) early 2024.

**Comment by opekope2** [comment]
LiLaC is now discontinued. [OptiGUI](https://github.com/opekope2/OptiGUI) 2.3.0-alpha.1 no longer requires it.
